### ISSUE TITLE
Command [Snapshot.getState] is unknown

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/Snapshot.ixi#6]
Cloned this project to ixi/Snapshot as described here: https://github.com/iotaledger/iri/pull/512
```
root@iota-full-node-01:/home/iota/node/ixi# ls Snapshot/
index.js  package.json  README.md
```

Milestone seems to be fine:
```
root@iota-full-node-01:/home/iota/node/ixi# /root/commands/getNodeInfo.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599  100   573  100    26   101k   4720 --:--:-- --:--:-- --:--:--  111k
{
  "appName": "IRI",
  "appVersion": "1.4.1.7",
  "jreAvailableProcessors": 8,
  "jreFreeMemory": 562205312,
  "jreVersion": "1.8.0_151",
  "jreMaxMemory": 13362528256,
  "jreTotalMemory": 2654994432,
  "latestMilestone": "KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999",
  "latestMilestoneIndex": 337541,
  "latestSolidSubtangleMilestone": "KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999",
  "latestSolidSubtangleMilestoneIndex": 337541,
  "neighbors": 5,
  "packetsQueueSize": 0,
  "time": 1517161315279,
  "tips": 5150,
  "transactionsToRequest": 93,
  "duration": 0
}
```

On executing the Snapshot.getState command I get the following error:
```
curl http://localhost:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json'   -d '{"command": "Snapshot.getState"}'
```
```
{ "error": "Command [Snapshot.getState] is unknown", "duration": 1 }
```

The iota.ini file:
```
PORT = 14265
UDP_RECEIVER_PORT = 14600
TCP_RECEIVER_PORT = 15600
API_HOST = 0.0.0.0
REMOTE_LIMIT_API="removeNeighbors, addNeighbors, interruptAttachingToTangle, attachToTangle, getNeighbors"
NEIGHBORS = tcp://* tcp://*
IXI_DIR = ixi
TESTNET = false
RESCAN_DB = false
HEADLESS = true
DEBUG = false
DB_PATH = mainnetdb
```

**Comment by Citrullin** [comment]
Restarted the node. It works now.

**Comment by maxmbed** [comment]
I am not able to run the validation script. I have the following error : 
```
COULD NOT PROCESS REQUEST! { Error: connect ECONNREFUSED 127.0.0.1:14265
at Object._errnoException (util.js:999:13)
at _exceptionWithHostPort (util.js:1020:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 14265 }
```

Port and address are correct though. 
Even after restart then cloning Snapshot.ixi
I have followed instructions : [https://gist.github.com/ralfr/f2dcfe4cb70ef7b85efab87c2640091e](url)

**Comment by Citrullin** [comment]
@maxmbed You had also the response 
```
{ "error": "Command [Snapshot.getState] is unknown", "duration": 1 }
```
right? Can you please provide the content of your .ini file? And the an ls -l output of your ixi folder with path. Just paste the bash output.

**Comment by maxmbed** [comment]
yes sure : 

`[IRI]
PORT = 14265
UDP_RECEIVER_PORT = 14600
TCP_RECEIVER_PORT = 15600
API_HOST = 0.0.0.0
IXI_DIR = ixi
HEADLESS = true
DEBUG = false
TESTNET = false
DB_PATH = mainnetdb
RESCAN_DB = false

#Tips to improve solid milestones syncing
#Found at https://github.com/iotaledger/iri/issues/214
P_REMOVE_REQUEST = 0.20
P_REPLY_RANDOM_TIP = 1.0
P_PROPAGATE_REQUEST = 0.01

#Enable API limit to :
REMOTE_LIMIT_API="removeNeighbors, addNeighbors, getNeighbors"
`
`/home/iota/ixi# ls -l
total 4
drwxr-xr-x 4 root root 4096 Jan 28 19:21 Snapshot
`
Yes, had the same output

**Comment by Citrullin** [comment]
@maxmbed Do you have any neighbors? Or are you using just Nelson? And you stopped the node and started it again? And checked the logs if the node really stopped and started?

**Comment by maxmbed** [comment]
I do not use Nelson. I have currently 5 connected neighbors. 

I use `journalctl -u iota -f` to see the log in real time. No error or specific thing occurred. 

I restart node with systemctl

**Comment by maxmbed** [comment]
When input `systemctl restart iota`, the log showed that IRI restarted properly.

**Comment by maxmbed** [comment]
Solved ! It was a dumb path issue. instead of /home/iota/node/ixi, my ixi folder was at /home/node/ixi...
